# Generated by Django 4.1.5 on 2023-01-30 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wcapi', '0003_widgetshome_widgetslock_delete_widgets'),
    ]

    operations = [
        migrations.CreateModel(
            name='WidgetsLockH',
            fields=[
                ('id_icon', models.AutoField(primary_key=True, serialize=False)),
                ('premium', models.CharField(default='off', max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('preview', models.FileField(null=True, upload_to='files/')),
                ('widj', models.FileField(null=True, upload_to='files/')),
                ('cat_slug', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'ИконкаПод',
                'verbose_name_plural': 'ИконкиПод',
            },
        ),
        migrations.CreateModel(
            name='WidgetsLockS',
            fields=[
                ('id_icon', models.AutoField(primary_key=True, serialize=False)),
                ('premium', models.CharField(default='off', max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('preview', models.FileField(null=True, upload_to='files/')),
                ('widj', models.FileField(null=True, upload_to='files/')),
                ('cat_slug', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'ИконкаПод',
                'verbose_name_plural': 'ИконкиПод',
            },
        ),
    ]
