# Generated by Django 4.1.5 on 2023-01-30 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wcapi', '0004_widgetslockh_widgetslocks'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WidgetsLockH',
            new_name='WidgetsHomeH',
        ),
    ]
