# Generated by Django 4.1.5 on 2023-01-30 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wcapi', '0005_rename_widgetslockh_widgetshomeh'),
    ]

    operations = [
        migrations.RenameField(
            model_name='widgetshomeh',
            old_name='widj',
            new_name='widgets',
        ),
        migrations.RenameField(
            model_name='widgetslocks',
            old_name='widj',
            new_name='widgets',
        ),
    ]
