# Generated by Django 4.1.5 on 2023-01-30 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wcapi', '0006_rename_widj_widgetshomeh_widgets_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='widgetshomeh',
            old_name='id_icon',
            new_name='id_Widgets',
        ),
        migrations.RenameField(
            model_name='widgetslocks',
            old_name='id_icon',
            new_name='id_Widgets',
        ),
    ]
