# Generated by Django 4.1.5 on 2023-02-09 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wcapi', '0007_rename_id_icon_widgetshomeh_id_widgets_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='icon',
            name='is_publish',
            field=models.CharField(default='off', max_length=255),
        ),
        migrations.AddField(
            model_name='theme',
            name='is_publish',
            field=models.CharField(default='off', max_length=255),
        ),
        migrations.AddField(
            model_name='wallpaper',
            name='is_publish',
            field=models.CharField(default='off', max_length=255),
        ),
        migrations.AddField(
            model_name='widgetshomeh',
            name='is_publish',
            field=models.CharField(default='off', max_length=255),
        ),
        migrations.AddField(
            model_name='widgetslocks',
            name='is_publish',
            field=models.CharField(default='off', max_length=255),
        ),
    ]
