# Generated by Django 4.1.5 on 2023-02-13 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wcapi', '0008_icon_is_publish_theme_is_publish_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='font',
            field=models.CharField(default='off', max_length=255),
        ),
        migrations.AddField(
            model_name='widgetshomeh',
            name='font',
            field=models.CharField(default='off', max_length=255),
        ),
        migrations.AddField(
            model_name='widgetslocks',
            name='font',
            field=models.CharField(default='off', max_length=255),
        ),
    ]
