# Generated by Django 4.1.5 on 2023-03-29 02:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wcapi', '0009_theme_font_widgetshomeh_font_widgetslocks_font'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theme',
            name='icons',
        ),
        migrations.RemoveField(
            model_name='theme',
            name='wallpaper',
        ),
        migrations.RemoveField(
            model_name='theme',
            name='widgets',
        ),
        migrations.AddField(
            model_name='icon',
            name='theme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='icons', to='wcapi.theme'),
        ),
        migrations.AddField(
            model_name='wallpaper',
            name='theme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wallpapers', to='wcapi.theme'),
        ),
        migrations.AddField(
            model_name='widgetshomeh',
            name='theme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='widget_homes', to='wcapi.theme'),
        ),
        migrations.AddField(
            model_name='widgetslocks',
            name='theme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='widget_locks', to='wcapi.theme'),
        ),
    ]
