# Generated by Django 4.1.5 on 2023-03-31 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wcapi', '0010_remove_theme_icons_remove_theme_wallpaper_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='widgetshomeh',
            options={'verbose_name': 'ВиджетHome', 'verbose_name_plural': 'ВиджетыHome'},
        ),
        migrations.AlterModelOptions(
            name='widgetslocks',
            options={'verbose_name': 'ВиджетLockS', 'verbose_name_plural': 'ВиджетыLockS'},
        ),
    ]
