# Generated by Django 4.1.5 on 2023-04-02 01:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('wcapi', '0011_alter_widgetshomeh_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('file', models.FileField(upload_to='config/', verbose_name='Файл')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
            ],
            options={
                'verbose_name': 'Конфигурационный файл',
                'verbose_name_plural': 'Конфигурационные файлы',
            },
        ),
    ]
