# Generated by Django 4.1.5 on 2023-04-02 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wcapi', '0012_mobileconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='widgetshomeh',
            name='needed_id_name',
            field=models.CharField(default='default', max_length=255),
        ),
        migrations.AddField(
            model_name='widgetslocks',
            name='needed_id_name',
            field=models.CharField(default='default', max_length=255),
        ),
    ]
